### ISSUE TITLE
Antwoorden op Exercises zouden erg handig zijn

### ISSUE THREAD

**Issue by ghost** [HansPhilippi/DB#1]
Elke individuele opdracht moeten bespreken met een student assistent ter verificatie is erg onaangenaam.

**Comment by huseyin38** [comment]
Hier ben ik heel erg mee eens!

**Comment by HansPhilippi** [comment]
Er verschijnen antwoorden, met enige vertraging. Daar is over nagedacht. Op dit moment zijn er antwoorden van sessies 1-3 beschikbaar via BB.
